# Generated by Django 3.2.5 on 2021-08-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210728_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='editdate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
